### ISSUE TITLE
Echo "$PWD" delivers output but Invalid next size

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#125]
![image](https://github.com/gysiang/minishell/assets/124663345/be0049c7-16a7-4217-ac5c-30999e074379)

**Comment by gysiang** [comment]
minishell$ echo "$PWD"
token: echo
token type: 0
token: $PWD
token type: 0
current token in process: echo
/home/gyong-si/Documents/42/minishell
minishell$ echo '$PWD'
token: echo
token type: 0
token: $PWD
token type: 0
current token in process: echo
/home/gyong-si/Documents/42/minishell

@axellee1994 my version does not trigger this error. echo '$PWD' still prints out the path which is wrong should print out '$PWD'
