### ISSUE TITLE
Echo "$PWD" memory overflow

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#131]
![image](https://github.com/gysiang/minishell/assets/124663345/54d68868-fb43-448a-b08e-f0325a5daa86)

@gysiang

**Comment by gysiang** [comment]
@axellee1994 I can't replicate this issue.

minishell$ echo "$PWD"
token: echo
token type: 0
token: $PWD
token type: 0
current token in process: echo
/home/gyong-si/Documents/42/minishell
minishell$ echo '$PWD'
token: echo
token type: 0
token: $PWD
token type: 0
current token in process: echo
/home/gyong-si/Documents/42/minishell
minishell$

**Comment by gysiang** [comment]
@axellee1994 can you start refactoring and norm the code you have done? I'll try to work on fixing some of the echo issue.

**Comment by gysiang** [comment]
@axellee1994 

void	process_dollar_character(char *str, char *result, int *i, int *j)
{
    t_shell	*minishell;
    char	next_char;
    char    exit_status[12];

    minishell = init_shell();
    
    This new minishell struct you init does not have the env variables. pass in minishell instead of init it again. Some of the functions need to use custom functions like sprintf, strlen, strcpy
