### ISSUE TITLE
DEADLY SIGNAL Issues when executing minishell

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#157]
![image](https://github.com/gysiang/minishell/assets/124663345/69a4a7e7-e8f2-40a6-941e-fa70103578ad)

Seems like a bug when running it with fsantize=address. Sometimes the error appears, sometimes it does not. 

The only way to resolve it for now is to exit and re-make/re-execute the minishell to proceed on

**Comment by gysiang** [comment]
Run this command with sudo.
**sudo sysctl vm.mmap_rnd_bits=28**

**Comment by gysiang** [comment]
@axellee1994 how do i run with santize address? the valgrind command suddenly don't work.
