### ISSUE TITLE
Memory issues regarding to Echo

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#177]
- [x] Testcase: echo hello world

- [x] Testcase: echo "hello world"

- [x] Testcase: echo 'hello world'

- [x] Testcase: echo hello"world"

- [x] Testcase: echo hello'world'

- [x] Testcase: echo hello""world

- [x] Testcase: echo hello''world

- [x] Testcase: echo '' (Single Quotes)

- [x] Testcase: echo "$PWD"

- [x] Testcase: echo '$PWD'

- [x] Testcase : echo "aspas ->'"

- [x] Testcase: echo "aspas -> ' " 

- [x] Testcase: echo 'aspas ->"'

- [x] Testcase: echo 'aspas -> " '

- [x] Testcase: echo "> >> < * ? [ ] | ; [ ] || && ( ) & # $ \ <<"

- [x] Testcase: echo '> >> < * ? [ ] | ; [ ] || && ( ) & # $ \ <<'

- [x] Testcase: echo "exit_code ->$? user ->$USER home -> $HOME"

- [x] Testcase: echo 'exit_code ->$? user ->$USER home -> $HOME'

- [x] Testcase: echo "$"

- [x] Testcase: echo '$'

- [x] Testcase: echo $

- [x] Testcase: echo $?

- [x] Testcase: echo $?HELLO

- [x] Testcase: echo -n hello

- [x] Testcase: cd src -> echo $PWD $OLDPWD

- [x] Testcase: echo "hi" | cat | cat | cat | cat | cat | cat | cat

- [x] Testcase: echo - "" "  " hello

- [x] echo test     \    test

- [x] echo backslash"test

- [x] echo "$TEST$TEST=lol$TEST"

- [x] echo "   $TEST lol $TEST"

- [ ] echo $TEST$TEST=lol$TEST""lol

- [x] echo test "" test "" test

- [x] echo "backslash$TEST"

- [x]  echo "$=TEST"

- [x] echo "$?TEST"

- [x]  echo "$1TEST"

- [x] echo '' test (single quote)

- [x] echo "hello , $USER" | grep hello > output.txt

**Comment by gysiang** [comment]
@axellee1994  I need some help in parsing this token to this.
token: grep ");"$ 
current output: );(space)$
should e grep );(no space)$
