### ISSUE TITLE
Segmentation fault with echo "word space wor

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#268]
minishell$ echo "$USER
$USER
minishell$ echo "normaltext
normaltext
minishell$ echo "normal text
Segmentation fault (core dumped)

minishell$ echo "normaltext
> hello
normaltext
minishell$ echo 'normaltext
normaltext
minishell$ echo 'normal text
Segmentation fault (core dumped)

Correct solution:

axlee@c1r5s3:~/Desktop/submission$ echo "normal text
> 
> 
> 
bash: unexpected EOF while looking for matching `"'
bash: syntax error: unexpected end of file
axlee@c1r5s3:~/Desktop/submission$ echo "normal text
> hello
> text
> "
normal text
hello
text
Will keep tying until close quotes 

axlee@c1r5s3:~/Desktop/submission$ 

Will segmentation fault when there is a space in between

**Comment by gysiang** [comment]
@axellee1994 I don't know why but this seems resolved.
