### ISSUE TITLE
Should not have executed ls and produce error instead. 

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#271]
minishell$ "   ls "
a.out	   libft      minishell_cmd	  no_permission.txt  output.txt     README.md
includes   Makefile   minishell.pdf	  obj		     path	    src
input.txt  minishell  no_permissioni.txt  outfile.txt	     readline.supp  tmp
minishell$ '     ls    '
a.out	   libft      minishell_cmd	  no_permission.txt  output.txt     README.md
includes   Makefile   minishell.pdf	  obj		     path	    src
input.txt  minishell  no_permissioni.txt  outfile.txt	     readline.supp  tmp
minishell$ 'ls'
a.out	   libft      minishell_cmd	  no_permission.txt  output.txt     README.md
includes   Makefile   minishell.pdf	  obj		     path	    src
input.txt  minishell  no_permissioni.txt  outfile.txt	     readline.supp  tmp

**Comment by gysiang** [comment]
@axellee1994 I'll take the redirects and you take the parser issues.
