### ISSUE TITLE
Double Quotes + Single Quotes_1

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#287]
Selvam Testcases:

echo "double"'single''"123"'"'456'"
doublesingle"123"'456'

Ours:
minishell$ echo "double"'single''"123"'"'456'"
double single "123" '456'

Execute a simple command
Then execute echo $? or $?$?
0+00

Ours return:
axlee@axlee:~/Desktop/42_minishell$ ./minishell
minishell$ echo $?+$?$?
0+ 0 0

Both issues stems in the minishell_echo where the space is being printed out. Need to write a command which keeps tracks of the space in the command line. If there is a space, print the space out. Else, do not print it.

**Comment by gysiang** [comment]
@axellee1994 I'll try to work on this tonight. The multiple heredoc feature i don't understand how to make it work.

**Comment by gysiang** [comment]
@axellee1994 ok if thats the case try pasting my code and test

minishell$ echo $?+$?$?
0+00

**Comment by gysiang** [comment]
@axellee1994  can you test out my echo branch? the tester shows 134/146 but when i tried out the command, it worked normally. echo $?+$?$? is resolved but echo "hello world will automatically print out " in the next line.
