### ISSUE TITLE
Double Quotes + Single Quotes_2

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#288]
Selvam Testcases:
axlee@axlee:~/Desktop/42_minishell$ echo $USER+’$HOME’+”$USER9999”
axlee+’/home/axlee’+””

Ours:
axlee@axlee:~/Desktop/42_minishell$ ./minishell
minishell$ echo $USER+echo $USER+’$HOME’+”$USER9999”
axlee +’$HOME’+”$USER9999”

**Comment by gysiang** [comment]
This seems like a wrong example, the single quoted $HOME should not expand at all. I copied into bash and it was not a single quote which is not required in the pdf.

**Comment by gysiang** [comment]
yes, i got the same result as your picture. That is not single quote.
