### ISSUE TITLE
Pipe Issues

### ISSUE THREAD

**Issue by axellee1994** [gysiang/minishell#82]
- [ ] Test case: echo "hi" | cat | cat | cat | cat | cat | cat | cat -> ps -a
      Our output: **Stuck in Zombie Process**

     **Bash Output**: hi 
      axlee@axlee:~/Desktop/42Cursus/minishell$ ps -a
          PID TTY          TIME CMD
         1835 tty2     00:00:00 gnome-session-b
         5593 pts/1    00:00:00 minishell
         5821 pts/1    00:00:00 minishell
         6304 pts/2    00:00:00 ps

**Comment by gysiang** [comment]
1. Need to integrate buildins into execute_command and pass the result to pipe
